fetch-api: Add missing version for connector-grafana

diff --git a/.github/workflows/fetch-api.yaml b/.github/workflows/fetch-api.yaml
--- a/.github/workflows/fetch-api.yaml
+++ b/.github/workflows/fetch-api.yaml
@@ -40,7 +40,18 @@ jobs:
 
     - name: Determine build version
       id: image_version
-      run: echo "VERSION=$(cat ${{ env.COMPONENT_PATH }}/VERSION)" >> $GITHUB_OUTPUT
+      run: |
+        VERSION_FILE=${{ env.COMPONENT_PATH }}/VERSION
+        VERSION=$(cat ${VERSION_FILE})
+
+        if [ $? -ne 0 ] || [ -z "$VERSION" ]; then
+          echo "${VERSION_FILE}: Failed to fetch version from file!"
+
+          exit 1
+        fi
+
+        echo "VERSION=${VERSION}" >> ${GITHUB_OUTPUT}
+        echo "Target image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"
 
     - name: Build and push image
       uses: docker/build-push-action@v6
